### ISSUE TITLE
Relax requirement of `torch`

### ISSUE THREAD

**Issue by mdancho84** [AlbertoAlmuinha/neuralprophet#10]
Suggest that the requirement of `torch==1.9.0` be relaxed to just `torch`. https://github.com/AlbertoAlmuinha/neuralprophet/blob/a07bf6b8a1a852d6d5520da66ccebe94b2985154/R/core-install.R#L48

The requirements file for `neural_prophet` is: https://github.com/ourownstory/neural_prophet/blob/master/requirements.txt

**Comment by AlbertoAlmuinha** [comment]
It's not a simple question this one...It's really wrong as it is now, since version 1.9.0 wouldn't do either (it has to be a torch version > 1.4 and lower 1.7). The problem is that the version that meets this is version 1.6.0 and for some reason there is no way to install it (or at least I have not been able to) through reticulate (when you see the available versions, 1.6.0 is not one of them). For this reason I had these lines of code before calling py_install with the packages, although it doesn't seem to be working:

https://github.com/AlbertoAlmuinha/neuralprophet/blob/5fb72b6850e65353387071b66eb656b84c1fbd44/R/core-install.R#L52-L56

In any case, I am afraid that if we are not able to install this version, it will be the users who will have to install it externally...

**Comment by mdancho84** [comment]
OK, can we do?
```
torch>=1.4.0
```

**Comment by AlbertoAlmuinha** [comment]
This doesn't work...the problem is the following:

- If I set this condition, then I automatically download torch==1.9.0 and then neuralprophet installation fails with the following error: `ERROR: Could not find a version that satisfies the requirement torch<1.7.0,>=1.4.0 (from neuralprophet) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0)`.
- As you can see, none of the versions that are theoretically available (`from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0`) meet the conditions of neuralprophet, so it is difficult to automate this installation step from R...(or at least I do not see how right now...).

The only solution I see right now is to install from outside torch version 1.6.0 by the user. Let me know if you see any other option.

**Comment by AlbertoAlmuinha** [comment]
This should be solved with the latest commit I've done!

Do you think it is a good time to migrate this package? What are next steps? I think it would be a good time to move and start soliciting feedback from users. I have also adapted the roles in the description so that I am the mantainer as we had discussed.
